=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/provider.definition.schema.v1.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://schema.cloudformation.us-east-1.amazonaws.com/provider.definition.schema.v1.json",
  "title": "CloudFormation Resource Provider Definition MetaSchema",
  "description": "This schema validates a CloudFormation resource provider definition.",
  "definitions": {
    "httpsUrl": {
      "type": "string",
      "pattern": "^https://[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])(:[0-9]*)*([?/#].*)?$",
      "maxLength": 4096
    },
    "handlerDefinition": {
      "description": "Defines any execution operations which can be performed on this resource provider",
      "type": "object",
      "properties": {
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalItems": false
        },
        "timeoutInMinutes": {
          "description": "Defines the timeout for the entire operation to be interpreted by the invoker of the handler.  The default is 120 (2 hours).",
          "type": "integer",
          "minimum": 2,
          "maximum": 2160,
          "default": 120
        }
      },
      "additionalProperties": false,
      "required": [
        "permissions"
      ]
    },
    "jsonPointerArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "format": "json-pointer"
      }
    },
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/properties"
      }
    },
    "validations": {
      "dependencies": {
        "enum": {
          "$comment": "Enforce that properties are strongly typed when enum, or const is specified.",
          "required": [
            "type"
          ]
        },
        "const": {
          "required": [
            "type"
          ]
        },
        "properties": {
          "$comment": "An object cannot have both defined and undefined properties; therefore, patternProperties is not allowed when properties is specified.",
          "not": {
            "required": [
              "patternProperties"
            ]
          }
        }
      }
    },
    "properties": {
      "allOf": [
        {
          "$ref": "#/definitions/validations"
        },
        {
          "$comment": "The following subset of draft-07 property references is supported for resource definitions. Nested properties are disallowed and should be specified as a $ref to a definitions block.",
          "type": "object",
          "properties": {
            "insertionOrder": {
              "description": "When set to true, this flag indicates that the order of insertion of the array will be honored, and that changing the order of the array would indicate a diff",
              "type": "boolean",
              "default": true
            },
            "$ref": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/$ref"
            },
            "$comment": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
            },
            "title": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/title"
            },
            "description": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/description"
            },
            "examples": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/examples"
            },
            "default": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/default"
            },
            "multipleOf": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/multipleOf"
            },
            "maximum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maximum"
            },
            "exclusiveMaximum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/exclusiveMaximum"
            },
            "minimum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minimum"
            },
            "exclusiveMinimum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/exclusiveMinimum"
            },
            "maxLength": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maxLength"
            },
            "minLength": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minLength"
            },
            "pattern": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/pattern"
            },
            "items": {
              "$comment": "Redefined as just a schema. A list of schemas is not allowed",
              "$ref": "#/definitions/properties",
              "default": {}
            },
            "maxItems": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maxItems"
            },
            "minItems": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minItems"
            },
            "uniqueItems": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/uniqueItems"
            },
            "contains": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/contains"
            },
            "maxProperties": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maxProperties"
            },
            "minProperties": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minProperties"
            },
            "required": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/required"
            },
            "properties": {
              "type": "object",
              "patternProperties": {
                "^[A-Za-z0-9]{1,64}$": {
                  "$ref": "#/definitions/properties"
                }
              },
              "additionalProperties": false,
              "minProperties": 1
            },
            "additionalProperties": {
              "$comment": "All properties of a resource must be expressed in the schema - arbitrary inputs are not allowed",
              "type": "boolean",
              "const": false
            },
            "patternProperties": {
              "$comment": "patternProperties allow providers to introduce a specification for key-value pairs, or Map inputs.",
              "type": "object",
              "propertyNames": {
                "format": "regex"
              }
            },
            "dependencies": {
              "$comment": "Redefined to capture our properties override.",
              "type": "object",
              "additionalProperties": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/properties"
                  },
                  {
                    "$ref": "https://json-schema.org/draft-07/schema#/definitions/stringArray"
                  }
                ]
              }
            },
            "const": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/const"
            },
            "enum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/enum"
            },
            "type": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/type"
            },
            "format": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/format"
            },
            "allOf": {
              "$ref": "#/definitions/schemaArray"
            },
            "anyOf": {
              "$ref": "#/definitions/schemaArray"
            },
            "oneOf": {
              "$ref": "#/definitions/schemaArray"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "resourceLink": {
      "type": "object",
      "properties": {
        "$comment": {
          "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
        },
        "templateUri": {
          "type": "string",
          "pattern": "^(/|https:)"
        },
        "mappings": {
          "type": "object",
          "patternProperties": {
            "^[A-Za-z0-9]{1,64}$": {
              "type": "string",
              "format": "json-pointer"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "templateUri",
        "mappings"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "patternProperties": {
    "^\\$id$": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/$id"
    }
  },
  "properties": {
    "$schema": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/$schema"
    },
    "type": {
      "$comment": "Resource Type",
      "type": "string",
      "const": "RESOURCE"
    },
    "typeName": {
      "$comment": "Resource Type Identifier",
      "examples": [
        "Organization::Service::Resource",
        "AWS::EC2::Instance",
        "Initech::TPS::Report"
      ],
      "type": "string",
      "pattern": "^[a-zA-Z0-9]{2,64}::[a-zA-Z0-9]{2,64}::[a-zA-Z0-9]{2,64}$"
    },
    "$comment": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
    },
    "title": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/title"
    },
    "description": {
      "$comment": "A short description of the resource provider. This will be shown in the AWS CloudFormation console.",
      "$ref": "https://json-schema.org/draft-07/schema#/properties/description"
    },
    "sourceUrl": {
      "$comment": "The location of the source code for this resource provider, to help interested parties submit issues or improvements.",
      "examples": [
        "https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-s3"
      ],
      "$ref": "#/definitions/httpsUrl"
    },
    "documentationUrl": {
      "$comment": "A page with supplemental documentation. The property documentation in schemas should be able to stand alone, but this is an opportunity for e.g. rich examples or more guided documents.",
      "examples": [
        "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/CHAP_Using.html"
      ],
      "$ref": "#/definitions/httpsUrl"
    },
    "additionalProperties": {
      "$comment": "All properties of a resource must be expressed in the schema - arbitrary inputs are not allowed",
      "type": "boolean",
      "const": false
    },
    "properties": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z0-9]{1,64}$": {
          "$ref": "#/definitions/properties"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "definitions": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z0-9]{1,64}$": {
          "$ref": "#/definitions/properties"
        }
      },
      "additionalProperties": false
    },
    "propertyTransform": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z0-9]{1,64}$": {
          "type": "string"
        }
      }
    },
    "handlers": {
      "description": "Defines the provisioning operations which can be performed on this resource type",
      "type": "object",
      "properties": {
        "create": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "read": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "update": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "delete": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "list": {
          "$ref": "#/definitions/handlerDefinition"
        }
      },
      "additionalProperties": false
    },
    "remote": {
      "description": "Reserved for CloudFormation use. A namespace to inline remote schemas.",
      "type": "object",
      "patternProperties": {
        "^schema[0-9]+$": {
          "description": "Reserved for CloudFormation use. A inlined remote schema.",
          "type": "object",
          "properties": {
            "$comment": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
            },
            "properties": {
              "$ref": "#/properties/properties"
            },
            "definitions": {
              "$ref": "#/properties/definitions"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false
    },
    "readOnlyProperties": {
      "description": "A list of JSON pointers to properties that are able to be found in a Read request but unable to be specified by the customer",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "writeOnlyProperties": {
      "description": "A list of JSON pointers to properties (typically sensitive) that are able to be specified by the customer but unable to be returned in a Read request",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "createOnlyProperties": {
      "description": "A list of JSON pointers to properties that are only able to be specified by the customer when creating a resource. Conversely, any property *not* in this list can be applied to an Update request.",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "deprecatedProperties": {
      "description": "A list of JSON pointers to properties that have been deprecated by the underlying service provider. These properties are still accepted in create & update operations, however they may be ignored, or converted to a consistent model on application. Deprecated properties are not guaranteed to be present in read paths.",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "primaryIdentifier": {
      "description": "A required identifier which uniquely identifies an instance of this resource type. An identifier is a non-zero-length list of JSON pointers to properties that form a single key. An identifier can be a single or multiple properties to support composite-key identifiers.",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "additionalIdentifiers": {
      "description": "An optional list of supplementary identifiers, each of which uniquely identifies an instance of this resource type. An identifier is a non-zero-length list of JSON pointers to properties that form a single key. An identifier can be a single or multiple properties to support composite-key identifiers.",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/jsonPointerArray"
      }
    },
    "required": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/required"
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "resourceLink": {
      "description": "A template-able link to a resource instance. AWS-internal service links must be relative to the AWS console domain. External service links must be absolute, HTTPS URIs.",
      "$ref": "#/definitions/resourceLink"
    }
  },
  "required": [
    "typeName",
    "properties",
    "description",
    "primaryIdentifier",
    "additionalProperties"
  ],
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/simple-service-aws.cfn.json
{
  "typeName": "AWS::SomeThing::FooResource",
  "description": "The Foo resource is cool.",
  "sourceUrl": "https://source.example.com",
  "documentationUrl": "https://docs.example.com",
  "definitions": {
    "ComplexProperty": {
      "type": "object",
      "properties": {
        "Property": {
          "type": "string"
        },
        "Another": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "FooDeprecatedMutableProperty": {
      "type": "string"
    },
    "FooId": {
      "type": "string"
    },
    "FooValidCreateProperty": {
      "type": "string"
    },
    "FooValidFullyMutableProperty": {
      "$ref": "#/definitions/ComplexProperty"
    },
    "FooValidReadProperty": {
      "type": "string"
    },
    "FooValidWriteProperty": {
      "type": "string"
    }
  },
  "readOnlyProperties": [
    "/properties/FooId",
    "/properties/FooValidReadProperty"
  ],
  "writeOnlyProperties": [
    "/properties/FooValidCreateProperty",
    "/properties/FooValidWriteProperty"
  ],
  "createOnlyProperties": [
    "/properties/FooValidCreateProperty"
  ],
  "deprecatedProperties": [
    "/properties/FooDeprecatedMutableProperty"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "otherservice:DescribeDependencyComponent",
        "something:CreateFooOperation"
      ]
    },
    "read": {
      "permissions": [
        "something:GetFooOperation"
      ]
    },
    "update": {
      "permissions": [
        "something:UpdateFooOperation"
      ]
    },
    "delete": {
      "permissions": [
        "something:DeleteFooOperation"
      ]
    },
    "list": {
      "permissions": [
        "something:ListFoosOperation"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/smithy-testservice-basil.cfn.json
{
  "typeName": "Smithy::TestService::Basil",
  "description": "This is an herb.",
  "properties": {
    "BarId": {
      "type": "string"
    },
    "BazExplicitMutableProperty": {
      "type": "string"
    },
    "BazId": {
      "type": "string"
    },
    "BazImplicitCreateProperty": {
      "type": "string"
    },
    "BazImplicitFullyMutableProperty": {
      "type": "string"
    },
    "BazImplicitReadProperty": {
      "type": "string"
    },
    "BazImplicitWriteProperty": {
      "type": "string"
    }
  },
  "readOnlyProperties": [
    "/properties/BarId",
    "/properties/BazId",
    "/properties/BazImplicitReadProperty"
  ],
  "writeOnlyProperties": [
    "/properties/BazImplicitWriteProperty"
  ],
  "createOnlyProperties": [
    "/properties/BazImplicitCreateProperty"
  ],
  "primaryIdentifier": [
    "/properties/BarId",
    "/properties/BazId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateBazOperation"
      ]
    },
    "read": {
      "permissions": [
        "testservice:GetBazOperation"
      ]
    },
    "update": {
      "permissions": [
        "testservice:UpdateBazOperation"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/smithy-testservice-bar.cfn.json
{
  "typeName": "Smithy::TestService::Bar",
  "description": "A Bar resource, not that kind of bar though.",
  "properties": {
    "Arn": {
      "type": "string"
    },
    "BarExplicitMutableProperty": {
      "type": "string"
    },
    "BarId": {
      "type": "string"
    },
    "BarImplicitFullProperty": {
      "type": "string"
    },
    "BarImplicitReadProperty": {
      "type": "string"
    },
    "BarValidAdditionalProperty": {
      "type": "string"
    }
  },
  "readOnlyProperties": [
    "/properties/Arn",
    "/properties/BarImplicitReadProperty"
  ],
  "createOnlyProperties": [
    "/properties/BarId"
  ],
  "primaryIdentifier": [
    "/properties/BarId"
  ],
  "additionalIdentifiers": [
    [
      "/properties/Arn"
    ]
  ],
  "handlers": {
    "create": {
      "permissions": [
        "otherservice:DescribeDependencyComponent",
        "testservice:PutBarOperation"
      ]
    },
    "read": {
      "permissions": [
        "testservice:GetBarOperation"
      ]
    },
    "update": {
      "permissions": [
        "otherservice:DescribeDependencyComponent",
        "testservice:PutBarOperation"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/create-write-mutability.cfn.json
{
  "typeName": "Smithy::TestService::CreateWrite",
  "description": "Definition of Smithy::TestService::CreateWrite Resource Type",
  "properties": {
    "CreateWriteProperty": {
      "type": "string"
    },
    "FooId": {
      "type": "string"
    }
  },
  "readOnlyProperties": [
    "/properties/FooId"
  ],
  "writeOnlyProperties": [
    "/properties/CreateWriteProperty"
  ],
  "createOnlyProperties": [
    "/properties/CreateWriteProperty"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateFoo"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/smithy-testservice-fooresource.cfn.json
{
  "typeName": "Smithy::TestService::FooResource",
  "description": "The Foo resource is cool.",
  "definitions": {
    "ComplexProperty": {
      "type": "object",
      "properties": {
        "Property": {
          "type": "string"
        },
        "Another": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "ConditionalProperty": {
      "oneOf": [
        {
          "type": "object",
          "title": "OptionOne",
          "properties": {
            "OptionOne": {
              "type": "string"
            }
          },
          "required": [
            "OptionOne"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "title": "OptionTwo",
          "properties": {
            "OptionTwo": {
              "type": "string"
            }
          },
          "required": [
            "OptionTwo"
          ],
          "additionalProperties": false
        }
      ]
    },
    "FooMap": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "ConditionalProperty": {
      "$ref": "#/definitions/ConditionalProperty"
    },
    "FooId": {
      "type": "string"
    },
    "FooValidCreateProperty": {
      "$ref": "#/definitions/FooMap"
    },
    "FooValidCreateReadProperty": {
      "type": "string"
    },
    "FooValidFullyMutableProperty": {
      "$ref": "#/definitions/ComplexProperty"
    },
    "FooValidReadProperty": {
      "type": "string"
    },
    "FooValidWriteProperty": {
      "type": "string"
    }
  },
  "readOnlyProperties": [
    "/properties/FooId",
    "/properties/FooValidReadProperty"
  ],
  "writeOnlyProperties": [
    "/properties/FooValidCreateProperty",
    "/properties/FooValidWriteProperty"
  ],
  "createOnlyProperties": [
    "/properties/FooValidCreateProperty",
    "/properties/FooValidCreateReadProperty"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateFooOperation"
      ]
    },
    "read": {
      "permissions": [
        "testservice:GetFooOperation"
      ]
    },
    "update": {
      "permissions": [
        "testservice:UpdateFooOperation"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/full-mutability.cfn.json
{
  "typeName": "Smithy::TestService::Full",
  "description": "Definition of Smithy::TestService::Full Resource Type",
  "properties": {
    "BarProperty": {
      "type": "string"
    },
    "FooId": {
      "type": "string"
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "readOnlyProperties": [
    "/properties/FooId"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateFoo"
      ]
    }
  },
  "additionalProperties": false
}
