=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/provider.definition.schema.v1.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://schema.cloudformation.us-east-1.amazonaws.com/provider.definition.schema.v1.json",
  "title": "CloudFormation Resource Provider Definition MetaSchema",
  "description": "This schema validates a CloudFormation resource provider definition.",
  "definitions": {
    "httpsUrl": {
      "type": "string",
      "pattern": "^https://[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])(:[0-9]*)*([?/#].*)?$",
      "maxLength": 4096
    },
    "handlerDefinition": {
      "description": "Defines any execution operations which can be performed on this resource provider",
      "type": "object",
      "properties": {
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalItems": false
        },
        "timeoutInMinutes": {
          "description": "Defines the timeout for the entire operation to be interpreted by the invoker of the handler.  The default is 120 (2 hours).",
          "type": "integer",
          "minimum": 2,
          "maximum": 2160,
          "default": 120
        }
      },
      "additionalProperties": false,
      "required": [
        "permissions"
      ]
    },
    "jsonPointerArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "format": "json-pointer"
      }
    },
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/properties"
      }
    },
    "validations": {
      "dependencies": {
        "enum": {
          "$comment": "Enforce that properties are strongly typed when enum, or const is specified.",
          "required": [
            "type"
          ]
        },
        "const": {
          "required": [
            "type"
          ]
        },
        "properties": {
          "$comment": "An object cannot have both defined and undefined properties; therefore, patternProperties is not allowed when properties is specified.",
          "not": {
            "required": [
              "patternProperties"
            ]
          }
        }
      }
    },
    "properties": {
      "allOf": [
        {
          "$ref": "#/definitions/validations"
        },
        {
          "$comment": "The following subset of draft-07 property references is supported for resource definitions. Nested properties are disallowed and should be specified as a $ref to a definitions block.",
          "type": "object",
          "properties": {
            "insertionOrder": {
              "description": "When set to true, this flag indicates that the order of insertion of the array will be honored, and that changing the order of the array would indicate a diff",
              "type": "boolean",
              "default": true
            },
            "$ref": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/$ref"
            },
            "$comment": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
            },
            "title": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/title"
            },
            "description": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/description"
            },
            "examples": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/examples"
            },
            "default": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/default"
            },
            "multipleOf": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/multipleOf"
            },
            "maximum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maximum"
            },
            "exclusiveMaximum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/exclusiveMaximum"
            },
            "minimum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minimum"
            },
            "exclusiveMinimum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/exclusiveMinimum"
            },
            "maxLength": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maxLength"
            },
            "minLength": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minLength"
            },
            "pattern": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/pattern"
            },
            "items": {
              "$comment": "Redefined as just a schema. A list of schemas is not allowed",
              "$ref": "#/definitions/properties",
              "default": {}
            },
            "maxItems": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maxItems"
            },
            "minItems": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minItems"
            },
            "uniqueItems": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/uniqueItems"
            },
            "contains": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/contains"
            },
            "maxProperties": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/maxProperties"
            },
            "minProperties": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/minProperties"
            },
            "required": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/required"
            },
            "properties": {
              "type": "object",
              "patternProperties": {
                "^[A-Za-z0-9]{1,64}$": {
                  "$ref": "#/definitions/properties"
                }
              },
              "additionalProperties": false,
              "minProperties": 1
            },
            "additionalProperties": {
              "$comment": "All properties of a resource must be expressed in the schema - arbitrary inputs are not allowed",
              "type": "boolean",
              "const": false
            },
            "patternProperties": {
              "$comment": "patternProperties allow providers to introduce a specification for key-value pairs, or Map inputs.",
              "type": "object",
              "propertyNames": {
                "format": "regex"
              }
            },
            "dependencies": {
              "$comment": "Redefined to capture our properties override.",
              "type": "object",
              "additionalProperties": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/properties"
                  },
                  {
                    "$ref": "https://json-schema.org/draft-07/schema#/definitions/stringArray"
                  }
                ]
              }
            },
            "const": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/const"
            },
            "enum": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/enum"
            },
            "type": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/type"
            },
            "format": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/format"
            },
            "allOf": {
              "$ref": "#/definitions/schemaArray"
            },
            "anyOf": {
              "$ref": "#/definitions/schemaArray"
            },
            "oneOf": {
              "$ref": "#/definitions/schemaArray"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "resourceLink": {
      "type": "object",
      "properties": {
        "$comment": {
          "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
        },
        "templateUri": {
          "type": "string",
          "pattern": "^(/|https:)"
        },
        "mappings": {
          "type": "object",
          "patternProperties": {
            "^[A-Za-z0-9]{1,64}$": {
              "type": "string",
              "format": "json-pointer"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "templateUri",
        "mappings"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "patternProperties": {
    "^\\$id$": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/$id"
    }
  },
  "properties": {
    "$schema": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/$schema"
    },
    "type": {
      "$comment": "Resource Type",
      "type": "string",
      "const": "RESOURCE"
    },
    "typeName": {
      "$comment": "Resource Type Identifier",
      "examples": [
        "Organization::Service::Resource",
        "AWS::EC2::Instance",
        "Initech::TPS::Report"
      ],
      "type": "string",
      "pattern": "^[a-zA-Z0-9]{2,64}::[a-zA-Z0-9]{2,64}::[a-zA-Z0-9]{2,64}$"
    },
    "$comment": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
    },
    "title": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/title"
    },
    "description": {
      "$comment": "A short description of the resource provider. This will be shown in the AWS CloudFormation console.",
      "$ref": "https://json-schema.org/draft-07/schema#/properties/description"
    },
    "sourceUrl": {
      "$comment": "The location of the source code for this resource provider, to help interested parties submit issues or improvements.",
      "examples": [
        "https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-s3"
      ],
      "$ref": "#/definitions/httpsUrl"
    },
    "documentationUrl": {
      "$comment": "A page with supplemental documentation. The property documentation in schemas should be able to stand alone, but this is an opportunity for e.g. rich examples or more guided documents.",
      "examples": [
        "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/CHAP_Using.html"
      ],
      "$ref": "#/definitions/httpsUrl"
    },
    "additionalProperties": {
      "$comment": "All properties of a resource must be expressed in the schema - arbitrary inputs are not allowed",
      "type": "boolean",
      "const": false
    },
    "properties": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z0-9]{1,64}$": {
          "$ref": "#/definitions/properties"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "definitions": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z0-9]{1,64}$": {
          "$ref": "#/definitions/properties"
        }
      },
      "additionalProperties": false
    },
    "propertyTransform": {
      "type": "object",
      "patternProperties": {
        "^[A-Za-z0-9]{1,64}$": {
          "type": "string"
        }
      }
    },
    "handlers": {
      "description": "Defines the provisioning operations which can be performed on this resource type",
      "type": "object",
      "properties": {
        "create": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "read": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "update": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "delete": {
          "$ref": "#/definitions/handlerDefinition"
        },
        "list": {
          "$ref": "#/definitions/handlerDefinition"
        }
      },
      "additionalProperties": false
    },
    "remote": {
      "description": "Reserved for CloudFormation use. A namespace to inline remote schemas.",
      "type": "object",
      "patternProperties": {
        "^schema[0-9]+$": {
          "description": "Reserved for CloudFormation use. A inlined remote schema.",
          "type": "object",
          "properties": {
            "$comment": {
              "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
            },
            "properties": {
              "$ref": "#/properties/properties"
            },
            "definitions": {
              "$ref": "#/properties/definitions"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false
    },
    "readOnlyProperties": {
      "description": "A list of JSON pointers to properties that are able to be found in a Read request but unable to be specified by the customer",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "writeOnlyProperties": {
      "description": "A list of JSON pointers to properties (typically sensitive) that are able to be specified by the customer but unable to be returned in a Read request",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "createOnlyProperties": {
      "description": "A list of JSON pointers to properties that are only able to be specified by the customer when creating a resource. Conversely, any property *not* in this list can be applied to an Update request.",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "deprecatedProperties": {
      "description": "A list of JSON pointers to properties that have been deprecated by the underlying service provider. These properties are still accepted in create & update operations, however they may be ignored, or converted to a consistent model on application. Deprecated properties are not guaranteed to be present in read paths.",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "primaryIdentifier": {
      "description": "A required identifier which uniquely identifies an instance of this resource type. An identifier is a non-zero-length list of JSON pointers to properties that form a single key. An identifier can be a single or multiple properties to support composite-key identifiers.",
      "$ref": "#/definitions/jsonPointerArray"
    },
    "additionalIdentifiers": {
      "description": "An optional list of supplementary identifiers, each of which uniquely identifies an instance of this resource type. An identifier is a non-zero-length list of JSON pointers to properties that form a single key. An identifier can be a single or multiple properties to support composite-key identifiers.",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/jsonPointerArray"
      }
    },
    "required": {
      "$ref": "https://json-schema.org/draft-07/schema#/properties/required"
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "resourceLink": {
      "description": "A template-able link to a resource instance. AWS-internal service links must be relative to the AWS console domain. External service links must be absolute, HTTPS URIs.",
      "$ref": "#/definitions/resourceLink"
    }
  },
  "required": [
    "typeName",
    "properties",
    "description",
    "primaryIdentifier",
    "additionalProperties"
  ],
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/queue-example.cfn.json
{
  "typeName": "Smithy::TestService::Queue",
  "description": "Definition of Smithy::TestService::Queue Resource Type",
  "definitions": {
    "RedrivePolicy": {
      "type": "object",
      "properties": {
        "MaxReceiveCount": {
          "type": "number"
        },
        "DeadLetterTargetArn": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "TagMap": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "Arn": {
      "type": "string"
    },
    "ContentBasedDeduplication": {
      "type": "boolean"
    },
    "DelaySeconds": {
      "type": "number",
      "maximum": 900,
      "minimum": 0
    },
    "FifoQueue": {
      "type": "boolean"
    },
    "KmsDataKeyReusePeriodSeconds": {
      "type": "number",
      "maximum": 86400,
      "minimum": 60
    },
    "KmsMasterKeyId": {
      "type": "string"
    },
    "MaximumMessageSize": {
      "type": "number",
      "maximum": 262144,
      "minimum": 1024
    },
    "MessageRetentionPeriod": {
      "type": "number",
      "maximum": 1209600,
      "minimum": 60
    },
    "QueueName": {
      "type": "string"
    },
    "ReceiveMessageWaitTimeSeconds": {
      "type": "number",
      "maximum": 20,
      "minimum": 0
    },
    "RedrivePolicy": {
      "$ref": "#/definitions/RedrivePolicy"
    },
    "Tags": {
      "$ref": "#/definitions/TagMap"
    },
    "URL": {
      "type": "string"
    },
    "VisibilityTimeout": {
      "type": "number",
      "maximum": 43200,
      "minimum": 0
    }
  },
  "readOnlyProperties": [
    "/properties/Arn",
    "/properties/URL"
  ],
  "createOnlyProperties": [
    "/properties/FifoQueue",
    "/properties/QueueName"
  ],
  "primaryIdentifier": [
    "/properties/QueueName"
  ],
  "additionalIdentifiers": [
    [
      "/properties/URL"
    ],
    [
      "/properties/Arn"
    ]
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateQueue"
      ]
    },
    "update": {
      "permissions": [
        "testservice:CreateQueue"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/complex-resource.cfn.json
{
  "typeName": "Smithy::TestService::Foo",
  "description": "Definition of Example::TestService::Foo Resource Type",
  "definitions": {
    "ArbitraryMap": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "ComplexProperty": {
      "type": "object",
      "properties": {
        "AnotherProperty": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "AddedProperty": {
      "type": "string"
    },
    "BarProperty": {
      "type": "string"
    },
    "CreateProperty": {
      "$ref": "#/definitions/ComplexProperty"
    },
    "CreateWriteProperty": {
      "$ref": "#/definitions/ArbitraryMap"
    },
    "CreatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "FooAlias": {
      "type": "string"
    },
    "FooId": {
      "type": "string"
    },
    "ImmutableSetting": {
      "type": "boolean"
    },
    "MutableProperty": {
      "$ref": "#/definitions/ComplexProperty"
    },
    "Password": {
      "type": "string"
    },
    "ReadProperty": {
      "$ref": "#/definitions/ComplexProperty"
    },
    "Secret": {
      "type": "string"
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "UpdatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "WriteProperty": {
      "$ref": "#/definitions/ComplexProperty"
    }
  },
  "readOnlyProperties": [
    "/properties/CreatedAt",
    "/properties/FooId",
    "/properties/ReadProperty",
    "/properties/UpdatedAt"
  ],
  "writeOnlyProperties": [
    "/properties/CreateWriteProperty",
    "/properties/Password",
    "/properties/Secret",
    "/properties/WriteProperty"
  ],
  "createOnlyProperties": [
    "/properties/CreateProperty",
    "/properties/CreateWriteProperty",
    "/properties/ImmutableSetting"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "additionalIdentifiers": [
    [
      "/properties/FooAlias"
    ]
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateFoo"
      ]
    },
    "read": {
      "permissions": [
        "testservice:GetFoo"
      ]
    },
    "update": {
      "permissions": [
        "testservice:UpdateFoo"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/nested-properties.cfn.json
{
    "typeName": "Smithy::TestService::Forecast",
    "description": "Definition of Smithy::TestService::Forecast Resource Type",
    "properties": {
        "ChanceOfRain": {
            "type": "number"
        },
        "ForecastId": {
            "type": "string"
        }
    },
    "createOnlyProperties": [
        "/properties/ForecastId"
    ],
    "primaryIdentifier": [
        "/properties/ForecastId"
    ],
    "handlers": {
        "create": {
            "permissions": [
                "testservice:CreateForecast",
                "testservice:PutForecast"
            ]
        },
        "read": {
            "permissions": [
                "testservice:GetForecast"
            ]
        },
        "update": {
            "permissions": [
                "testservice:PutForecast",
                "testservice:UpdateForecast"
            ]
        }
    },
    "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/read-mutability.cfn.json
{
  "typeName": "Smithy::TestService::Read",
  "description": "Definition of Smithy::TestService::Read Resource Type",
  "properties": {
    "CreatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "FooId": {
      "type": "string"
    },
    "UpdatedAt": {
      "type": "string",
      "format": "date-time"
    }
  },
  "readOnlyProperties": [
    "/properties/CreatedAt",
    "/properties/FooId",
    "/properties/UpdatedAt"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "read": {
      "permissions": [
        "testservice:GetFoo"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/write-mutability.cfn.json
{
  "typeName": "Smithy::TestService::Write",
  "description": "Definition of Smithy::TestService::Write Resource Type",
  "properties": {
    "FooId": {
      "type": "string"
    },
    "Password": {
      "type": "string"
    },
    "Secret": {
      "type": "string"
    }
  },
  "readOnlyProperties": [
    "/properties/FooId"
  ],
  "writeOnlyProperties": [
    "/properties/Password",
    "/properties/Secret"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateFoo"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/disable-caps-fooresource.cfn.json
{
  "typeName": "Smithy::TestService::FooResource",
  "description": "The Foo resource is cool.",
  "definitions": {
    "ComplexProperty": {
      "type": "object",
      "properties": {
        "another": {
          "type": "string"
        },
        "property": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "ConditionalProperty": {
      "oneOf": [
        {
          "type": "object",
          "title": "optionOne",
          "properties": {
            "optionOne": {
              "type": "string"
            }
          },
          "required": [
            "optionOne"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "title": "optionTwo",
          "properties": {
            "optionTwo": {
              "type": "string"
            }
          },
          "required": [
            "optionTwo"
          ],
          "additionalProperties": false
        }
      ]
    },
    "FooMap": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "conditionalProperty": {
      "$ref": "#/definitions/ConditionalProperty"
    },
    "fooId": {
      "type": "string"
    },
    "fooValidCreateProperty": {
      "$ref": "#/definitions/FooMap"
    },
    "fooValidCreateReadProperty": {
      "type": "string"
    },
    "fooValidFullyMutableProperty": {
      "$ref": "#/definitions/ComplexProperty"
    },
    "fooValidReadProperty": {
      "type": "string"
    },
    "fooValidWriteProperty": {
      "type": "string"
    }
  },
  "createOnlyProperties": [
    "/properties/fooValidCreateProperty",
    "/properties/fooValidCreateReadProperty"
  ],
  "readOnlyProperties": [
    "/properties/fooId",
    "/properties/fooValidReadProperty"
  ],
  "writeOnlyProperties": [
    "/properties/fooValidCreateProperty",
    "/properties/fooValidWriteProperty"
  ],
  "primaryIdentifier": [
    "/properties/fooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:CreateFooOperation"
      ]
    },
    "read": {
      "permissions": [
        "testservice:GetFooOperation"
      ]
    },
    "update": {
      "permissions": [
        "testservice:UpdateFooOperation"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/put-lifecycle.cfn.json
{
  "typeName": "Smithy::TestService::PutResource",
  "description": "Definition of Smithy::TestService::PutResource Resource Type",
  "properties": {
    "BarProperty": {
      "type": "string"
    },
    "FooId": {
      "type": "string"
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "createOnlyProperties": [
    "/properties/FooId"
  ],
  "primaryIdentifier": [
    "/properties/FooId"
  ],
  "handlers": {
    "create": {
      "permissions": [
        "testservice:PutFoo"
      ]
    },
    "update": {
      "permissions": [
        "testservice:PutFoo"
      ]
    }
  },
  "additionalProperties": false
}

=== smithy-lang/smithy/smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/required-output.cfn.json
{
    "typeName": "Smithy::TestService::RequiredOutput",
    "description": "Definition of Smithy::TestService::RequiredOutput Resource Type",
    "properties": {
        "FooId": {
            "type": "string"
        },
        "LastUpdate": {
            "type": "string",
            "format": "date-time"
        },
        "Tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "Tags"
    ],
    "readOnlyProperties": [
        "/properties/FooId",
        "/properties/LastUpdate"
    ],
    "createOnlyProperties": [
        "/properties/Tags"
    ],
    "primaryIdentifier": [
        "/properties/FooId"
    ],
    "handlers": {
        "create": {
            "permissions": [
                "testservice:CreateFoo"
            ]
        },
        "read": {
            "permissions": [
                "testservice:ReadFoo"
            ]
        }
    },
    "additionalProperties": false
}
